{
    "currentPage": 1,
    "numberOfPages": 1,
    "totalResults": 5,
    "data": [
        {
            "id": "xjjDoA",
            "name": "Brewpub",
            "streetAddress": "2323 N Milwaukee Ave",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60647",
            "phone": "773-227-2739",
            "website": "http://revbrew.com/",
            "hoursOfOperation": "Mon-Fri: 11am-2am\r\nSat: 10am-3am\r\nSun: 10am-2am",
            "latitude": 41.923363,
            "longitude": -87.698071,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "brewpub",
            "locationTypeDisplay": "Brewpub",
            "countryIsoCode": "US",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:42:07",
            "updateDate": "2014-07-23 19:11:34",
            "breweryId": "PHkaP0",
            "brewery": {
                "id": "PHkaP0",
                "name": "Revolution Brewing",
                "nameShortDisplay": "Revolution",
                "description": "Revolution Brewing is Chicago's new hometown craft brewery. Our brewpub in Logan Square is a bustling, neighborhood institution where friends and families meet to enjoy the freshest beer in town. Opening our brewery has been a labor of love. We think you can see that in everything we do ranging from the details of our carved fists holding up our mahogany bar to the pungent hop aroma of our Anti-Hero IPA to our creative dishes like our bacon-fat popcorn.\r\n\r\nThe growth of craft breweries in the U.S. has been nothing short of a revolution and we're proud to be standing tall in this new crowd. The changing tastes of beer drinkers demand bigger flavors and more variety. That's exactly what we give you at Revolution Brewing. Our brewpub produces about 50 different beer styles each year. We've got session beers like Workingman Mild, hop-bombs like Double Fist and more bourbon barrel aged beers than you can shake a stave at. We have fun doing what we do and invite you to come in and join us.",
                "website": "http://revbrew.com/",
                "established": "2010",
                "isOrganic": "N",
                "images": {
                    "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/PHkaP0/upload_X9hrAl-icon.png",
                    "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/PHkaP0/upload_X9hrAl-medium.png",
                    "large": "https://s3.amazonaws.com/brewerydbapi/brewery/PHkaP0/upload_X9hrAl-large.png",
                    "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/PHkaP0/upload_X9hrAl-squareMedium.png",
                    "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/PHkaP0/upload_X9hrAl-squareLarge.png"
                },
                "status": "verified",
                "statusDisplay": "Verified",
                "createDate": "2012-01-03 02:42:07",
                "updateDate": "2015-12-22 14:55:57"
            },
            "country": {
                "isoCode": "US",
                "name": "UNITED STATES",
                "displayName": "United States",
                "isoThree": "USA",
                "numberCode": 840,
                "createDate": "2012-01-03 02:41:33"
            }
        },
        {
            "id": "Kd6WH6",
            "name": "Main Brewery",
            "streetAddress": "4257 N. Lincoln Ave",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60618",
            "phone": "773-248-4038",
            "website": "http://www.halfacrebeer.com/",
            "hoursOfOperation": "Tue - Fri:\t12:00 pm - 8:00 pm\r\nSat:\t11:00 am - 7:00 pm\r\nSun:\t12:00 pm - 5:00 pm",
            "latitude": 41.9592701,
            "longitude": -87.6823099,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "micro",
            "locationTypeDisplay": "Micro Brewery",
            "countryIsoCode": "US",
            "yearOpened": "2006",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:41:56",
            "updateDate": "2014-07-23 19:11:34",
            "breweryId": "lZfiot",
            "brewery": {
                "id": "lZfiot",
                "name": "Half Acre Beer Company",
                "nameShortDisplay": "Half Acre",
                "description": "Half Acre Beer Co. is a brewing company in the Northcenter neighborhood of Chicago, IL. We built a brewery in the middle of the city where we brew small batch beers, and have a store & tasting area where we sample our beers and sell them to go in all package styles. \r\n\r\nWe make different beers throughout the year, some we brew all the time and some are only around for a very short period. Our focus is to expand our abilities and enjoy our work.",
                "website": "http://www.halfacrebeer.com/",
                "established": "2006",
                "mailingListUrl": "HELLO@HALFACREBEER.COM",
                "isOrganic": "N",
                "images": {
                    "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/lZfiot/upload_jQLFRi-icon.png",
                    "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/lZfiot/upload_jQLFRi-medium.png",
                    "large": "https://s3.amazonaws.com/brewerydbapi/brewery/lZfiot/upload_jQLFRi-large.png",
                    "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/lZfiot/upload_jQLFRi-squareMedium.png",
                    "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/lZfiot/upload_jQLFRi-squareLarge.png"
                },
                "status": "verified",
                "statusDisplay": "Verified",
                "createDate": "2012-01-03 02:41:56",
                "updateDate": "2015-12-22 15:04:24"
            },
            "country": {
                "isoCode": "US",
                "name": "UNITED STATES",
                "displayName": "United States",
                "isoThree": "USA",
                "numberCode": 840,
                "createDate": "2012-01-03 02:41:33"
            }
        },
        {
            "id": "yolHh5",
            "name": "Main Brewery",
            "streetAddress": "5121 N Ravenswood Ave",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60640",
            "website": "http://www.metrobrewing.com/",
            "latitude": 41.9749341,
            "longitude": -87.6742738,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "micro",
            "locationTypeDisplay": "Micro Brewery",
            "countryIsoCode": "US",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:42:02",
            "updateDate": "2014-07-23 19:11:34",
            "breweryId": "wi2NVb",
            "brewery": {
                "id": "wi2NVb",
                "name": "Metropolitan Brewing",
                "nameShortDisplay": "Metropolitan",
                "description": "From day one, every drop of Metro beer has been brewed and packaged by us, in our warehouse production brewery in the Ravenswood Industrial Corridor of Chicago. We're proud Chicagoans, honored to be offering up fresh lagers to the Chicagoland area.",
                "website": "http://www.metrobrewing.com/",
                "isOrganic": "N",
                "images": {
                    "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/wi2NVb/upload_KCqbzW-icon.png",
                    "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/wi2NVb/upload_KCqbzW-medium.png",
                    "large": "https://s3.amazonaws.com/brewerydbapi/brewery/wi2NVb/upload_KCqbzW-large.png",
                    "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/wi2NVb/upload_KCqbzW-squareMedium.png",
                    "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/wi2NVb/upload_KCqbzW-squareLarge.png"
                },
                "status": "verified",
                "statusDisplay": "Verified",
                "createDate": "2012-01-03 02:42:02",
                "updateDate": "2015-12-22 14:52:05"
            },
            "country": {
                "isoCode": "US",
                "name": "UNITED STATES",
                "displayName": "United States",
                "isoThree": "USA",
                "numberCode": 840,
                "createDate": "2012-01-03 02:41:33"
            }
        },
        {
            "id": "R2I4D5",
            "name": "Main Brewery",
            "streetAddress": "737 W Randolph St",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60661",
            "phone": "312-638-0700",
            "website": "http://www.haymarketbrewing.com/",
            "latitude": 41.884044,
            "longitude": -87.647162,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "brewpub",
            "locationTypeDisplay": "Brewpub",
            "countryIsoCode": "US",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:41:57",
            "updateDate": "2014-07-23 19:11:34",
            "breweryId": "5PsLiM",
            "brewery": {
                "id": "5PsLiM",
                "name": "Haymarket Pub & Brewery",
                "nameShortDisplay": "Haymarket Pub",
                "description": "Specializing in classic Belgian and contemporary American beer styles, Pete crafts an array of brews for every beer palette. Crowley, a highly decorated brewer has won over 50 local, national and international awards for his brewing creations including medals from the World Beer Cup, Great American Beer Festival and Festival of Wood and Barrel Aged Beer. Varieties range from refreshing Pilsners to hoppy ales as well as rich Imperial Stouts aged in whiskey barrels in our own cellar; a brewing technique that has put Crowley on the national beer map for his pioneering work with the specialty. Our impressive array of 32 tap handles behind the bar feature more than 10 house brewed varieties as well as guest drafts with a focus on local.",
                "website": "http://www.haymarketbrewing.com/",
                "established": "2010",
                "isOrganic": "N",
                "images": {
                    "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/5PsLiM/upload_41Aask-icon.png",
                    "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/5PsLiM/upload_41Aask-medium.png",
                    "large": "https://s3.amazonaws.com/brewerydbapi/brewery/5PsLiM/upload_41Aask-large.png",
                    "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/5PsLiM/upload_41Aask-squareMedium.png",
                    "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/5PsLiM/upload_41Aask-squareLarge.png"
                },
                "status": "verified",
                "statusDisplay": "Verified",
                "createDate": "2012-01-03 02:41:57",
                "updateDate": "2015-12-22 15:09:58"
            },
            "country": {
                "isoCode": "US",
                "name": "UNITED STATES",
                "displayName": "United States",
                "isoThree": "USA",
                "numberCode": 840,
                "createDate": "2012-01-03 02:41:33"
            }
        },
        {
            "id": "wbpj5b",
            "name": "Main Brewery",
            "streetAddress": "1675 N Western Ave",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60647",
            "phone": "773-725-9428",
            "website": "http://www.pipeworksbrewing.com/",
            "latitude": 41.912447,
            "longitude": -87.686905,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "micro",
            "locationTypeDisplay": "Micro Brewery",
            "countryIsoCode": "US",
            "yearOpened": "2009",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:42:05",
            "updateDate": "2014-07-23 19:11:34",
            "breweryId": "fz3g3i",
            "brewery": {
                "id": "fz3g3i",
                "name": "Pipeworks Brewing Company",
                "nameShortDisplay": "Pipeworks",
                "description": "Pipeworks began, as many breweries do, in the stove top kettles and plastic-bucket fermenters of the home brewer. Beejay Oslon and Gerrit Lewis met while working at Chicago's famous West Lakeview Liquors, a haven for beer geeks in search of new and exciting brews from around the world. While working there, the two got to thinking it was time to turn their passion in to a business.\r\n\r\n The first steps in that long journey  took them to a the small town of Lo in the Belgian countryside. It was there that the Pipeworks boys lived and worked with Urbain Coutteau owner and brewer at the De Struise Brewery. While working there the boys honed their craft, learned the ins and outs of running a brewery, and had the opportunity to create their first commercially available beers. The success of these brews fueled their passion and prepared them for the work ahead of them.\r\n\r\n Upon coming back to the States the two began experimenting with pilot batches, formulating a business plan, and developing an image for Pipeworks.\r\n\r\n Now we are ready to bring what we've learned to the craft beer world!",
                "website": "http://www.pipeworksbrewing.com/",
                "established": "2009",
                "isOrganic": "N",
                "images": {
                    "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/fz3g3i/upload_pFeJAW-icon.png",
                    "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/fz3g3i/upload_pFeJAW-medium.png",
                    "large": "https://s3.amazonaws.com/brewerydbapi/brewery/fz3g3i/upload_pFeJAW-large.png",
                    "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/fz3g3i/upload_pFeJAW-squareMedium.png",
                    "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/fz3g3i/upload_pFeJAW-squareLarge.png"
                },
                "status": "verified",
                "statusDisplay": "Verified",
                "createDate": "2012-01-03 02:42:05",
                "updateDate": "2015-12-22 15:04:15"
            },
            "country": {
                "isoCode": "US",
                "name": "UNITED STATES",
                "displayName": "United States",
                "isoThree": "USA",
                "numberCode": 840,
                "createDate": "2012-01-03 02:41:33"
            }
        }
    ],
    "status": "success"
}
